Perk p3 single
DanielDoehring/Trixi.jl pull request #26
Opened 2024-03-21 13:25 UTC by warisa-r

Hello,

I added the constructor, and some tests, and edited Project.toml. Some of these are in the same files that are being edited in PERK2 so I think it will result in some conflicts but that's probably not a big deal. Please let me know if I'm missing something or need to fix something. Thank you in advance!

2024-03-21 14:16 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +    # Both terms should be present
```suggestion
    # Compute stability polynomial according to Butcher Tableau
```

2024-03-21 14:19 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +function PERK3_butcher_tableau_objective_function(a_unknown, num_stages,
```suggestion
function PERK3_Butcher_tableau_objective_function(a_unknown, num_stages,
```

I guess we can write names in capitals.

2024-03-21 14:19 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +function compute_PERK3_butcher_tableau(num_stages, tspan, eig_vals::Vector{ComplexF64},
```suggestion
function compute_PERK3_Butcher_tableau(num_stages, tspan, eig_vals::Vector{ComplexF64},
```

2024-03-21 14:20 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +
```suggestion
```

2024-03-21 14:22 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +            x0 = 0.1 .* rand(num_stages)
This might lead to troubles at testing, maybe we need to change this to something fixed. But let's see.

2024-03-21 14:22 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +function compute_PERK3_butcher_tableau(num_stages, base_path_mon_coeffs::AbstractString,
```suggestion
function compute_PERK3_Butcher_tableau(num_stages, base_path_mon_coeffs::AbstractString,
```

2024-03-21 14:32 UTC, DanielDoehring requested changes
Nice work so far! I added some minor changes.

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +    println("\n")
```suggestion
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +        newPERK3.a_matrix, newPERK3.c = compute_PERK3_butcher_tableau(num_stages,
```suggestion
        newPERK3.a_matrix, newPERK3.c = compute_PERK3_Butcher_tableau(num_stages,
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +        newPERK3.a_matrix, newPERK3.c = compute_PERK3_butcher_tableau(num_stages, tspan,
```suggestion
        newPERK3.a_matrix, newPERK3.c = compute_PERK3_Butcher_tableau(num_stages, tspan,
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +        newPERK3.a_matrix, newPERK3.c = compute_PERK3_butcher_tableau(num_stages, tspan,
```suggestion
        newPERK3.a_matrix, newPERK3.c = compute_PERK3_Butcher_tableau(num_stages, tspan,
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +    k_s1::uType # Required for third order
```suggestion
    k_s1::uType # Required for custom third order version of PERK3
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +The following structures and methods provide a minimal implementation of
```suggestion
The following structures and methods provide a implementation of
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +optimized for a certain simulation setup (PDE, IC & BC, Riemann Solver, DG Solver).
```suggestion
optimized for a certain simulation setup (PDE, IC & BC, Riemann Solver, DG Solver).

The original paper is
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +"""
```suggestion

While the changes to SSPRK33 base-scheme are described in 
- Doehring, Schlottke-Lakemper, Gassner, Torrilhon (2024)
Multirate Time-Integration based on Dynamic ODE Partitioning through Adaptively Refined Meshes for Compressible Fluid Dynamics
[Arxiv: 10.48550/arXiv.2403.05144](https://doi.org/10.48550/arXiv.2403.05144)
"""
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/methods_PERK3.jl
> +
```suggestion
```

2024-03-21 14:32 UTC, DanielDoehring commented on src/time_integration/paired_explicit_runge_kutta/polynomial_optimizer.jl
> +end
This is probably no longer needed, right?

2024-03-21 14:32 UTC, DanielDoehring commented on examples/structured_1d_dgsem/elixir_burgers_PERK3.jl
> +solver = DGSEM(polydeg = 4, surface_flux = flux_lax_friedrichs)
Maybe we use indeed p=3 as this is the standard degree for most examples.

In that case, you can maybe increase `CFL` below.

2024-05-25 15:59 UTC, warisa-r commented
Close this one in order to prepare for the version with NLsolve extension and further improvements

2024-05-25 15:59 UTC, warisa-r commented
Close this one in order to prepare for the version with NLsolve extension and further improvements

2024-05-25 15:59 UTC, closed without merging